#!/bin/bash

clear
echo ""
echo -e "\e[94m ============================================================ "
echo -e "\e[94m ============================================================ "
echo -e "\e[92m              ██╗  ██╗██╗  ██╗███████╗███████╗        "
echo -e "\e[92m              ██║  ██║██║  ██║╚══███╔╝╚══███╔╝        "
echo -e "\e[92m              ███████║███████║  ███╔╝   ███╔╝         "
echo -e "\e[92m              ██╔══██║╚════██║ ███╔╝   ███╔╝          "
echo -e "\e[92m              ██║  ██║     ██║███████╗███████╗        "
echo -e "\e[92m              ╚═╝  ╚═╝     ╚═╝╚══════╝╚══════╝        "
echo -e "       ║ For Debian 9 & Debian 10 64 bit                  ║     "
echo -e "       ║ For Ubuntu 18.04 & Ubuntu 20.04 64 bit           ║     "
echo -e "       ║ For VPS with KVM and VMWare virtualization       ║     "
echo -e "       ║ Build Up By XC0D3-X                              ║     "
echo -e "       ║ Thank you Allah for Everything                   ║     "
echo -e "\e[94m ============================================================ "
echo -e "\e[94m ============================================================ "
echo ""
